name: liver_tumor_train
image_channels: 1
fold: 0
dataset_list: ['PET_CT_tumour_train']
data_root_path: ../../DiffTumor_data/Autopet/
label_root_path: ../../DiffTumor_data/Autopet/
data_txt_path: ../../DiffTumor_data/Autopet/
dist: False
batch_size: 4
num_workers: 0 # should be 8, but reduced so that no error comes out

a_min: -175
a_max: 250
b_min: -1.0
b_max: 1.0
space_x: 1.0
space_y: 1.0
space_z: 1.0
roi_x: 96
roi_y: 96
roi_z: 96
num_samples: 10
phase: train
uniform_sample: False
datasetkey: ['10_03']
cache_dataset: True
cache_rate: 0.001 #1
