vqgan_ckpt: /data/lychan/24_Summer_Research/DiffTumor/STEP1.AutoencoderModel/checkpoints/vq_gan/synt/AutoPET_with_val/lightning_logs/version_1/checkpoints/latest_checkpoint-v1.ckpt

# Have to be derived from VQ-GAN Latent space dimensions
diffusion_img_size: 24
diffusion_depth_size: 24
diffusion_num_channels: 17
out_dim: 8
dim_mults: [1,2,4,8]
results_folder: checkpoints/ddpm/
results_folder_postfix: AutoPET_1 #'fold0_tumor_early_96_t4'
load_milestone: /data/lychan/24_Summer_Research/DiffTumor/STEP2.DiffusionModel/checkpoints/ddpm/liver_tumor_train/AutoPET_1/10.pt

batch_size: 2 # 40
num_workers: 0
logger: wandb
objective: pred_x0
save_and_sample_every: 5 #1000
denoising_fn: Unet3D
train_lr: 1e-4
timesteps: 4 # number of steps
sampling_timesteps: 250 # number of sampling timesteps (using ddim for faster inference [see citation for ddim paper])
loss_type: l1 # L1 or L2
train_num_steps: 60000 # total training steps
gradient_accumulate_every: 2 # gradient accumulation steps
ema_decay: 0.995 # exponential moving average decay
amp: False # turn on mixed precision
num_sample_rows: 1
gpus: [0, 1, 2, 3]
